[Wish-Korea] 장바구니 delete 기능 구현
wecode-bootcamp-korea/34-1st-Wish-Korea-backend pull request #11
Opened 2022-06-27 06:52 UTC by dingwan0331

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ x ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장바구니 delete 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. delete메소드를 사용하여 카트의 object를 삭제
<br />

2022-06-28 02:00 UTC, lordmyshepherd requested changes

2022-06-28 02:00 UTC, lordmyshepherd commented on orders/views.py
> +            return JsonResponse({'message' : 'Invalid Item'}, status = 400)
KeyError와 IntegrityError 에러는 발생할 일이 없어 보입니다.

2022-06-28 06:02 UTC, lordmyshepherd requested changes

2022-06-28 06:02 UTC, lordmyshepherd commented on products/views.py
> +    @token_decorator
여기는 데코레이터 제거해주세요.

2022-06-28 06:02 UTC, lordmyshepherd commented on orders/views.py
> +            return JsonResponse({'message' : 'No Content'}, status = 201)
```suggestion
            return JsonResponse({'message' : 'No Content'}, status = 200)
            return HttpResponse(status = 204)
```

2022-06-28 08:48 UTC, lordmyshepherd requested changes

2022-06-28 08:48 UTC, lordmyshepherd commented on products/views.py
> +    @token_decorator
아직 데코레이터가 남아있습니다!

2022-06-28 08:48 UTC, lordmyshepherd commented on orders/views.py
> +class CartView(View):
여기는 데코레이터가 필요해요!

2022-06-28 08:48 UTC, lordmyshepherd commented on orders/views.py
> +            Cart.objects.get(id = cart_id).delete()
```suggestion
            Cart.objects.get(id = cart_id, user_id = request.user.id).delete()
```

2022-06-28 09:05 UTC, dingwan0331 commented
제가 아까 말씀드린 깃이 꼬인사항이라 정신이 없네요..
혹시      Cart.objects.get(id = cart_id).delete()
            Cart.objects.get(id = cart_id, user_id = request.user.id).delete()
            
 이부분이
 
Cart.objects.get(id = cart_id, user = request.user).delete()
이런식으로 사용한다면 성능부분에서 차이가 있을까요?!

2022-06-28 10:03 UTC, Kang-kyunghun commented on orders/views.py
> +            return JsonResponse({'message' : 'No Content'}, status = 200)
No content에 대한 상태 코드는 204입니다.
상태 코드 다시 한 번 확인해 주세요.

```suggestion

            return JsonResponse({'message' : 'No Content'}, status = 204)
```

2022-06-28 10:06 UTC, Kang-kyunghun commented on orders/views.py
> +            return JsonResponse({'message' : 'Invalid Cart'}, status = 400)
데이터가 존재 하지 않을 때 상태코든 주로 404를 사용합니다.
상태 코드에 대해서 조금 더 학습하면 좋을 것 같습니다.

```suggestion
        except Cart.DoesNotExist:
            return JsonResponse({'message' : 'Invalid Cart'}, status = 404)
```

2022-06-29 01:28 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-06-29 01:28 UTC, merged