[Wish-Korea] 장바구니 patch 기능 구현
wecode-bootcamp-korea/34-1st-Wish-Korea-backend pull request #12
Opened 2022-06-27 06:55 UTC by dingwan0331

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ x ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장바구니 patch 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. cart_id 는 path params 사용
2. quantity는 query params 사용
3. 재고와 수량 비교후 quantity 보다 재고가 더 많다면 cart 수량 변경
<br />

2022-06-28 02:02 UTC, lordmyshepherd requested changes

2022-06-28 02:02 UTC, lordmyshepherd commented on orders/views.py
> +            quantity = int(requset.GET.get('quantity'))
보통 patch에 필요한 데이터를 body로 받습니다.

```suggestion
            quantity = int(requset.GET.get('quantity'))
```

2022-06-28 02:02 UTC, lordmyshepherd commented on orders/views.py
> +            return JsonResponse({'message' : 'Key Error'}, status = 400)
코드 상에서 KeyError가 어디서 발생할 수 있나요?

2022-06-29 15:49 UTC, dingwan0331 commented
현재 delete 기능은 path params로 CartView에서 처리하고있고
patch도 CartView에서 처리하고 있지만 path params가 존재하지않아 url 주소를 두종류로 사용하였습니다.

2022-06-30 01:10 UTC, lordmyshepherd requested changes

2022-06-30 01:10 UTC, lordmyshepherd commented on orders/views.py
> +            if cart.quantity + data.get('quantity') <= 0:
Line 23~24 코드가 왜 필요한가요?

어떤 케이스인지 알려주실 수 있을까요?

2022-06-30 01:37 UTC, dingwan0331 commented on orders/views.py
> +            if cart.quantity + data.get('quantity') <= 0:
어제기준으로 프론트에서 장바구니에 상품갯수가 0 일때 -버튼이 눌려도 통신이와서 해당사항에대해서 에러메세지 반환할려고 작성했는데
오늘 스탠드업미팅때 들으니 프론트측에서 통신자체가 설정했다고 해서 해당부분 삭제하고 다시 올립니다.

2022-06-30 04:30 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-06-30 04:30 UTC, merged