[Wish-Korea]상품 리스트 API 구현
wecode-bootcamp-korea/34-1st-Wish-Korea-backend pull request #6
Opened 2022-06-23 15:25 UTC by dingwan0331

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ x ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 리스트 API 카테고리 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상품 리스트 구현
- 쿼리 파라미터를통해 sub_category id를 받아서 해당 리스트의 정보를 주보여주는 API를 작성했습니다.

2. size 옵션 갯수에 따라 product name을 다르게 작성
- size옵션이 1개면 이름 그대로를 반환
- size옵션이 2개 이상이면 이름 뒤에 'product.name /size_g/size_g' 형식으로 반환 하였습니다.
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 이름에 size를 붙여서 반환하는것을 list Comprehesions 내부에서 하려고 고민을오래했었는데
- setdfault로 따로 코드를짜서 해도 된다는걸 깨달았습니다.
- 반복문 돌릴때 변수이름 설정과 Json 키값 지정이 제일 어려운것 같습니다...

<br />

## :: 기타 질문 및 특이 사항
- products.models.Imgae 클래스 오타가났는데... 원래 models 브랜치에서 수정 후 다시 푸시하면 될까요..!?
- `sizes  = [size_value.size.size_g for size_value in product.item_set.all()]
     name = product.name
     sizes.sort()`
     이부분 장고 orm으로 order_by 하고 싶었는데 제 코드가 더 복잡해지는것 같아서 sort() 함수를 썼는데 더 좋은 접근이 있을까요?!

2022-06-25 06:00 UTC, dingwan0331 commented
CategoryView 구현중에 카테고리(SubCategory X)에 속한 모든 프로덕트 갯수를 구할려고 아래의 코드를썼는데 
'products_count' : sum([i.product_set.all().count() for i in category.subcategory_set.all()]), 
장고 orm으로 처리하는 방법있을까요 ... 어제부터 찾다가 머리털이 6가닥 정도 빠진것 같아요

2022-06-28 02:14 UTC, lordmyshepherd requested changes

2022-06-28 02:14 UTC, lordmyshepherd commented on products/views.py
> +                # products = Product.objects.filter(sub_category_id = request.GET['sub_category_id'])
주석은 지우고 다시 올려주세요.

2022-06-28 02:14 UTC, lordmyshepherd commented on products/views.py
> +            # if request.GET.get('category_id'):
사용하지 않는 코드 주석은 지우고 다시 올려주세요.

2022-06-28 07:07 UTC, lordmyshepherd requested changes

2022-06-28 07:07 UTC, lordmyshepherd commented on products/views.py
> +        categories = Category.objects.all()
```suggestion
        categories = Category.objects.all().annotate(product_counts=Count("subcategory__product__id"))
```

2022-06-28 07:07 UTC, lordmyshepherd commented on products/views.py
> +                    product__sub_category__in = category.subcategory_set.all()).count(),
```suggestion
                'products_count' : category.product_counts,
```

2022-06-28 07:07 UTC, lordmyshepherd commented on products/views.py
> +                # products = Product.objects.filter(sub_category_id = request.GET['sub_category_id'])
```suggestion
            category_id = request.GET.get('category_id')
            sub_category_id = request.GET.get('sub_category_id')
            
            q = Q()
            
            if category_id:
                q &= Q(sub_category__category_id = category_id)

            if sub_category_id:
                q  &= Q(sub_category_id = category_id)
            
            products = Product.objects.filter(q)
```

2022-06-28 10:00 UTC, merged